// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RssAtomFid.Api.DAL;

namespace RssAtomFid.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190406201333_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RssAtomFid.Api.DAL.Entity.Account.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired();

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired();

                    b.Property<string>("UserName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RssAtomFid.Api.DAL.Entity.Feed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<int>("FeedsCategoryId");

                    b.Property<int?>("FeedsCollectionId");

                    b.Property<string>("Guid");

                    b.Property<string>("Link");

                    b.Property<string>("Media");

                    b.Property<string>("PubDate");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("FeedsCollectionId");

                    b.ToTable("Feeds");
                });

            modelBuilder.Entity("RssAtomFid.Api.DAL.Entity.FeedsCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment");

                    b.Property<string>("Title");

                    b.Property<int>("TotalCount");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("FeedsCollection");
                });

            modelBuilder.Entity("RssAtomFid.Api.DAL.Entity.Feed", b =>
                {
                    b.HasOne("RssAtomFid.Api.DAL.Entity.FeedsCollection")
                        .WithMany("Feeds")
                        .HasForeignKey("FeedsCollectionId");
                });

            modelBuilder.Entity("RssAtomFid.Api.DAL.Entity.FeedsCollection", b =>
                {
                    b.HasOne("RssAtomFid.Api.DAL.Entity.Account.User")
                        .WithMany("FeedCollections")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
